egutter:
  twitter: egutter
  github: egutter
  full_name: Emilio Gutter 
  company: 10Pines
  title: The Agile City Building Game
  abstract: |
    Are you ready to start building your own city? Join a construction team, take your tools and 
    get ready to build a fantastic city while you learn fundamental principles of Lean software 
    development. You an your team will have to maximize value delivered to the people in your 
    city while you compete with other teams to show which is the best agile building team! The 
    objective of this games is to let you experience the fundamental principles behind Lean/Agile 
    software development while you have fun and learn with your partners. During the game, each 
    team will have to mockup buildings and objects in the city, using simple materials provided 
    by the organizers. Teams will get a story backlog, each one with an assigned business value. 
    Each team will carry out the stories within short iterations in order to maximize the value 
    delivered by the end of the game. 
  bio: |
    Emilio is one of 10Pines co-founders. He has been working in software development area for more 
    than 10 years, participating in several projects for Argentina; Brazil; United Kingdom; United 
    States; France; Romania and Bulgaria. He has performed as software developer; project leader 
    and agile coach with experience in different industries such as credit services; media & 
    entertainment; advertising; travel & leisure among others. Also, he is strongly committed 
    with the local Agile community and he is a member of the organization team of the Latin 
    American "Agiles" conference since 2008, being in Agiles 2012 the conference co-chair.

martinsalias:
  twitter: martinsalias
  github: martinsalias
  full_name: Martín Salias 
  company: Kleer
  title: Yoseki Coding Dojo
  abstract: |
    El Dojo es, en la tradición japonesa, el lugar destinado a la enseñanza y el perfeccionamiento 
    en las artes marciales y la meditación. Yoseki es donde se localizan los auxiliares del maestro 
    y aquellos estudiantes avanzados. Es donde todo aprendiz quiere llegar. La iniciativa del 
    Coding Dojo se está difundiendo rápidamente en muchas ciudades del mundo. Su filosofía se trata 
    de aprender, aprender y aprender. En nuestro Coding Dojo nos reunimos para resolver Coding 
    Katas (ejercicios de programación) trabajando de a pares (y rotando con diferentes patrones) 
    y basando la práctica en TDD.
  bio: |
    Martín lleva 30 años dedicado a la construcción de software y ha trabajado en proyectos a lo 
    largo de América, Australia y Europa, para organizaciones tan variadas como las Naciones Unidas 
    o Microsoft Corp. Ha desarrollado en diversas plataformas y lenguajes como C++, Fox, Java, 
    COBOL, .NET, Python, Ruby y otros. Es uno de los Trainers y Coaches en Kleer, una organización 
    latinoamericana dedicada a difundir mejores prácticas organizacionales relacionadas a la 
    construcción de software y otros productos basados en innovación en equipos.

dariocravero:
  twitter: dariocravero
  github: dariocravero
  full_name: Darío Javier Cravero 
  company: UXtemple
  title: Understanding deployments
  abstract: |
    This workshop is a hands on, scratch the surface and dive deep into how to deploy your 
    applications into production. Knowing how things work is the first step towards understanding 
    what went wrong when your platform blew up at four in the morning that crazy Saturday. The 
    deployment environment is your platform's home and as its landlord you should know how to build 
    it from the ground up and keep it nice and tidy so that the tenants live happily ever after :). 
  bio: |
    CTO @ UXtemple. Padrino core mantainer. Yoga lover and mate drinker.

damianmarti:
  twitter: damianmarti
  github: damianmarti
  full_name: Damián Martinelli
  company: Sumavisos
  title: Introducción a NoSQL
  abstract: |
    El taller consiste en una introducción a los diferentes tipos de base de datos no relacionales, 
    como ser clave/valor, por columnas, de documentos, de grafos. Contando las caracteristicas 
    principales de cada una, cuándo es útil, cuándo no, y ejemplos de motores de base de datos 
    disponibles para cada tipo.
    Cada vez se habla más de NoSQL y cada vez se utilizan más base de datos de este tipo, pero hay 
    muchos programadores que todavia no las conocen o solo la conocen de oido, sin conocer qué es 
    cada una y cuando es útil utilizarlas.
  bio: |
    Soy Ingeniero en Informática recibido en la UBA. Programo desde el GWBasic y estoy en el 
    mundo de la programación web desde hace alrededor de 15 años. Programé en Pascal, Delphi, 
    C, Java, PHP, pero cuando me metí en el mundo Ruby de la mano de Rails allá por el 2006, 
    nunca más quise tocar otro lenguaje. Soy uno de los fundadores de Sumavisos, un buscador 
    de avisos clasificados presente en 30 países, y el CTO. 

tutec:
  twitter: tutec
  github: tute
  full_name: Tute Costa
  company: General Assembly
  title: 'Simplificando código: de monstruo a elegante en tres simples pasos!'
  abstract: |
    Todos tenemos muertos en el placard, o vimos los muertos de otros. En este taller voy a mostrar 
    en vivo cómo modificar código altamente acoplado y difícil de entender, mostrando cómo transformar 
    código inmantenible hacia código bello, siguiendo y tendiendo a patrones, para resultar en un bello 
    unicornio que cumple con las cuatro reglas de Sandi Metz, sin grandes dolores de cabeza, sin 
    refactoreos "big bang", y divirtiéndonos.
  bio: |
    Mantengo los proyectos <a href="https://github.com/tute/merit" target="_blank">merit</a> y
    <a href="https://github.com/applicake/doorkeeper" target="_blank">doorkeeper</a>. Creé una app 
    para saber dónde estoy y qué me rodea: <a href="http://dynamicatlas.herokuapp.com/" target="_blank">
    dynamicatlas</a>. Trabajo en <a href="https://generalassemb.ly/">General Assembly</a>.

luke_ar:
  twitter: luke_ar
  github: delucas
  full_name: Lucas Videla
  company: Uno21
  title: 'TDD IRL // git y GitHub: primeros pasos'
  abstract: |
    TDD IRL: Taller para experimentar junto a los asistentes el uso y esencia de TDD en Ruby. Vamos a hacer 
    un ejemplo juntos, y luego lo harán crecer viendo la potencia de tener la red de contención que los 
    tests proporcionan. Está pensado para gente que domine el lenguaje, aunque no conozca las herramientas 
    de testing. 
    //
    git y GitHub: Presentación de la herramienta emblemática para cualquier desarrollador que se desempeñe 
    en la industria. El formato taller permite que los asistentes se lleven git andando y preparado, con 
    una inmersión de un par de horas y algunos logros que los inicien e inspiren continuidad en el camino 
    hacia seguir utilizándo la herramienta.
  bio: |
    Un aprendiz incansable del arte de la programación. Trato de llevar mis conocimientos desde y hacia 
    diversos ámbitos, aprovechándolos más allá de la tecnología. Docente en dos universidades, encargado 
    de enseñar las bases de la programación a jóvenes de 17 a 6x años (porque no llegó nadie más grande). 
    Algunos de mis proyectos: <a href="braid.herokuapp.com" target="_blank">Braid</a> y 
    <a href="github.com/delucas/notas" target="_blank">Notas del Taller de Java</a>.
