sintaxi:
  twitter: sintaxi
  full_name: Brock Whitten
  company: Harp platform
tef:
  twitter: tef
  full_name: Thomas Edward Figg
  company: Code Club
cherkaos:
  twitter: cherkaos
  full_name: Ostap Cherkashin
  company: Mingle
janogonzalez:
  twitter: janogonzalez
  full_name: Jano González
  company: HopIn
hyper_linda:
  twitter: hyper_linda
  full_name: Linda Sandvik
  company: Code Club
poteland:
  twitter: poteland
  full_name: Pablo Astigarraga
  company: Vivid Cortex
kurko:
  twitter: kurko
  full_name: Alexandre de Oliveira
  company: Stack Builders
saltinejustine:
  twitter: saltinejustine
  full_name: Justine Arreche
  company: 
runixo:
  twitter: runixo
  full_name: Martin Sarsale
  company: Sumavisos/Properati
ajlopez:
  twitter: ajlopez
  full_name: Angel 'Java' Lopez
  company: Southworks
plexus:
  twitter: plexus
  full_name: Arne Brasseur
  company: 
hannelita:
  twitter: hannelita
  full_name: Hanneli Tavante
  company: TFG
spastorino:
  twitter: spastorino
  full_name: Santiago Pastorino
  company: WyeWorks
thiagopradi:
  twitter: thiagopradi
  full_name: Thiago Pradi
  company: 
abecciu:
  twitter: abecciu
  full_name: Augusto Becciu
  company: Restorando
androbtech:
  twitter: androbtech
  full_name: Andres Robalino
  company: Andrab
cuerbot:
  twitter: cuerbot
  full_name: Bruno cuerbot
  company: Neo
