site_lang:
  en: en
  es: es
nav_home:
  en: Home
  es: Inicio
nav_speakers:
  en: Speakers
  es: Oradores
nav_venue:
  en: Venue
  es: Lugar
nav_sponsors:
  en: Sponsors
  es: Sponsors
nav_lang_selector_url:
  en: /es
  es: /en
nav_lang_selector_message:
  en: ¿Hablas español?
  es: Do you speak English?
date:
  en: November 27 &amp; 28, 2013
  es: 27 y 28 de Noviembre, 2013
header:
  en: |
        We are very proud to announce the third edition of RubyConf Argentina,<br>
        a regional conference about Ruby and related technologies.
  es: |
        Estamos orgullosos de anunciar la tercer edición de RubyConf Argentina,<br>
        una conferencia regional sobre Ruby y tecnologías relacionadas.
register:
  en: Register now!
  es: Registrate ahora!
price_legend:
  en: (about USD 88), upto October 11th
  es: (aprox. USD 88), hasta el 11 de octubre
ticket_includes:
  en: "Your ticket includes: access to all sessions during the conference, breakfasts, lunches and coffee breaks, official T-shirt, access to Ruby Fun Day"
  es: "Tu entrada incluye: Acceso a todas las charlas durante los dos días de conferencia, desayunos, almuerzos y coffee breaks, camiseta oficial de la conferencia, acceso al Ruby Fun Day"
cfp_title:
  en: Speakers &amp; Call for Proposals
  es: Oradores &amp; Convocatoria de Propuestas
cfp_text:
  en: "<strong>The Call for Proposals is closed!</strong><br>We appreciate all of the submissions we've received. We are currently reviewing them, and will be responding by 9/22."
  es: "<strong>La convocatoria a oradores ha finalizado!</strong><br>Agradecemos mucho todas las propuestas recibidas. Estamos evaluando cada una de ellas y las estaremos respondiendo a partir del 22/9."
cfp_link:
  en: Send your proposal before September 13th!
  es: Envianos tu propuesta antes del 13 de Septiembre!
venue_title:
  en: Venue
  es: Lugar
venue_text:
  en: This year the event returns to
  es: Este año el evento vuelve a
sponsors_title:
  en: Sponsors
  es: Sponsors
sponsors_text:
  en: Rubyists love those companies that support the community!
  es: ¡Los Rubyistas amamos a las organizaciones que apoyan a la comunidad!
contact_us:
  en: Email us
  es: Envianos un email
sponsors_text_closure:
  en: to discuss how your company can be part of this great opportunity.
  es: y te contaremos cómo tu empresa puede aprovechar esta gran oportunidad.
footer_first:
  en: RubyConf Argentina is organized by
  es: RubyConf Argentina es organizada por
footer_end:
  en: a non-profit organization dedicated to promoting the growth of Ruby and related technologies
  es: una asociación sin fines de lucro dedicada a promover el crecimiento de Ruby y teconologías relacionadas
past_editions:
  en: Past events
  es: Eventos anteriores
